### PR TITLE
React Material UI

### PR DESCRIPTION
**Pull request by changalberto**
Here's the initial react material ui for the example app.

### CODE REVIEW

**Comment by MightyAlex200** [comment]
Great! Thanks for this. I'm not sure what needs to be done to update this to `0.0.12-alpha` (if anything at all), so I'll leave that up to you, but I've also added a function `get_username` to get the username of any given agent: 98cf7be29b92f786ad166c9f1a2f95d97155515f.

Also, when I was thinking of posts on threads, I was thinking along the lines of online forums like discourse (i.e. posts are chronologically arranged in a vertical manner, rather than in a card style.)

**Comment by changalberto** [comment]
@MightyAlex200 Let's upgrade to `0.0.12-alpha` from your fork and test to see if `remove_skill` works. And then I'll make adjustments as needed on my end later.

And I'll change the posts to vertical chronological order as you described.

**Comment by changalberto** [comment]
@MightyAlex200 Give this a quick test. If is good, we should merge this PR.

**Comment by changalberto** [comment]
@MightyAlex200 There's a bug with `get_my_skills`. After you `remove_skill` and try calling `get_my_skills` again, you'll get `InternalFailure(RibosomeFailed("WASM invocation failed: Trap: Trap { kind: Unreachable }"))`

**Comment by MightyAlex200** [comment]
Sorry for the delay, everything looks good and I've created a fix for the error when removing skills.

**Pull request merged**
